# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # setting environment variables, if needed
    env:
      NODE_ENV: development
      DB_HOST: localhost
      DB_USER: root
      DB_PASS: root
      DB_NAME: cicdtest
      PORT: 3333
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Mysql
      run: |
        sudo systemctl start mysql
        mysql -u root -proot < db/create-db.sql 
    - name: Use Node.js ${{ matrix.node-version }} in ${{env.NODE_ENV}} mode
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: ls
    - run: npm run build --if-present
    - run: npm run test
